In [2]:
import torch
import torch.nn.functional as F 


In [6]:
input_sequence = torch.tensor([[0.1, 0.2, 0.3, 0.5], [0.4, 0.5, 0.6, 0.7], [0.7, 0.8, 0.9, 1.0]])


In [11]:
random_weights_key = torch.randn(input_sequence.size(-1), input_sequence.size(-1))
random_weights_query = torch.randn(input_sequence.size(-1), input_sequence.size(-1))
random_weights_value = torch.randn(input_sequence.size(-1), input_sequence.size(-1))


In [41]:
# 计算 Key、Query 和 Value 矩阵
key = torch.matmul(input_sequence, random_weights_key)
query = torch.matmul(input_sequence, random_weights_query)
value = torch.matmul(input_sequence, random_weights_value)



In [68]:
attention_scores = torch.matmul(query, key.T) / torch.sqrt(torch.tensor(query.size(-1), dtype=torch.float32))
attention_scores

tensor([[-0.6722, -0.8577, -1.1768],
        [-1.0108, -1.2007, -1.6163],
        [-1.4273, -1.6372, -2.1814]])

In [67]:
attention_weights = F.softmax(attention_scores, dim=-1)
attention_weights

tensor([[0.4108, 0.3412, 0.2480],
        [0.4214, 0.3485, 0.2300],
        [0.4384, 0.3554, 0.2062]])

In [64]:
torch.matmul(query, key.T) / torch.sqrt(torch.tensor(query.size(-1), dtype=torch.float32))

tensor([[-0.6722, -0.8577, -1.1768],
        [-1.0108, -1.2007, -1.6163],
        [-1.4273, -1.6372, -2.1814]])

In [90]:
output = torch.matmul(attention_weights, value)
output

tensor([[-1.5961, -1.5240,  0.7995, -0.3255],
        [-1.5702, -1.4992,  0.7820, -0.3243],
        [-1.5336, -1.4642,  0.7570, -0.3227]])

In [37]:
import torch
scalar = torch.randn(())
print(scalar)  # 一个服从标准正态分布的随机数

tensor(-0.0923)


In [40]:
import torch

# 创建一个张量并启用 requires_grad
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# 进行一些操作
y = x + 2
z = y * y * 2
out = z.mean()

print("x:", x)
print("y:", y)
print("z:", z)
# print("out:", out)

# 反向传播计算梯度
z.backward(gradient=z)


# x 的梯度 (存储在 x.grad 中)
print("x.grad:", x.grad)


x: tensor([1., 2., 3.], requires_grad=True)
y: tensor([3., 4., 5.], grad_fn=<AddBackward0>)
z: tensor([18., 32., 50.], grad_fn=<MulBackward0>)
x.grad: tensor([ 216.,  512., 1000.])


In [81]:
x = torch.rand(2, 3, 4, 5)
x

tensor([[[[0.2398, 0.4022, 0.5029, 0.1586, 0.6830],
          [0.2595, 0.7700, 0.0521, 0.2001, 0.1069],
          [0.4462, 0.6837, 0.6259, 0.7133, 0.4479],
          [0.9324, 0.8798, 0.6851, 0.4031, 0.9305]],

         [[0.0546, 0.0280, 0.2939, 0.1642, 0.8514],
          [0.3091, 0.3258, 0.1811, 0.9448, 0.4614],
          [0.6802, 0.3815, 0.2783, 0.3688, 0.0626],
          [0.4162, 0.9296, 0.5085, 0.9594, 0.5284]],

         [[0.8062, 0.9262, 0.0049, 0.8470, 0.8719],
          [0.1529, 0.3640, 0.5178, 0.1427, 0.6948],
          [0.9093, 0.9645, 0.9951, 0.0249, 0.3401],
          [0.5244, 0.4705, 0.8384, 0.6986, 0.3982]]],


        [[[0.3143, 0.2618, 0.3191, 0.8092, 0.8274],
          [0.1319, 0.4903, 0.8877, 0.0393, 0.4391],
          [0.2902, 0.6614, 0.3019, 0.0026, 0.3177],
          [0.4606, 0.7559, 0.7139, 0.1065, 0.6123]],

         [[0.3965, 0.7048, 0.6530, 0.6256, 0.8849],
          [0.8202, 0.9877, 0.7630, 0.2774, 0.4079],
          [0.0238, 0.1944, 0.6778, 0.4352, 0.4888],
  

In [82]:
y = F.softmax(x, dim=-1)
y

tensor([[[[0.1679, 0.1975, 0.2184, 0.1548, 0.2615],
          [0.1894, 0.3156, 0.1539, 0.1785, 0.1626],
          [0.1732, 0.2197, 0.2073, 0.2263, 0.1735],
          [0.2317, 0.2198, 0.1809, 0.1364, 0.2312]],

         [[0.1520, 0.1480, 0.1931, 0.1696, 0.3372],
          [0.1681, 0.1709, 0.1479, 0.3174, 0.1957],
          [0.2716, 0.2014, 0.1817, 0.1989, 0.1464],
          [0.1513, 0.2529, 0.1660, 0.2605, 0.1693]],

         [[0.2134, 0.2406, 0.0958, 0.2223, 0.2279],
          [0.1566, 0.1934, 0.2256, 0.1550, 0.2693],
          [0.2424, 0.2562, 0.2641, 0.1001, 0.1372],
          [0.1856, 0.1759, 0.2541, 0.2209, 0.1636]]],


        [[[0.1596, 0.1515, 0.1604, 0.2619, 0.2667],
          [0.1464, 0.2095, 0.3117, 0.1334, 0.1990],
          [0.1909, 0.2767, 0.1931, 0.1432, 0.1962],
          [0.1819, 0.2444, 0.2343, 0.1277, 0.2117]],

         [[0.1529, 0.2081, 0.1976, 0.1923, 0.2492],
          [0.2288, 0.2706, 0.2161, 0.1330, 0.1515],
          [0.1387, 0.1645, 0.2667, 0.2093, 0.2208],
  

In [88]:
z = y.sum(dim=-1)
z

tensor([[[1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000]],

        [[1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000]]])

In [93]:
import math 
import torch 
import torch.nn as nn 
import torch.optim as optim 
import torch.nn.functional as F 


In [ ]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000) -> None:
        super().__init__()
        
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)

In [98]:
a = torch.arange(0,20)
b = torch.randn(20)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [102]:
b.type

'torch.FloatTensor'

In [99]:
b

tensor([ 0.0252, -1.3866, -0.2124,  0.1827,  0.0384, -1.7722, -0.1030,  0.2198,
         0.2870, -0.2933,  0.5405, -0.8020,  2.1565, -0.0025,  0.3317, -0.4555,
        -0.9157,  1.1668, -1.0764,  0.4816])

In [97]:
a.shape

torch.Size([20])

In [103]:
a = torch.randn(2,3)
a

tensor([[-0.8150, -0.2135, -0.2431],
        [ 0.0481, -0.4257, -1.2807]])

In [104]:
a.transpose(-1,-2)

tensor([[-0.8150,  0.0481],
        [-0.2135, -0.4257],
        [-0.2431, -1.2807]])

In [ ]:
a.T

In [1]:
import torch
import torch.nn as nn 
from torch.utils.data import Dataset, DataLoader

In [2]:
input_size = 5 
output_size = 2 
batch_size = 30
data_size = 200


In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [5]:
class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
    
    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

In [6]:
rand_loader = DataLoader(dataset=RandomDataset(input_size, data_size),batch_size=batch_size, shuffle=True)


In [7]:
class Model(nn.Module):
    def __init__(self, input_size, output_size) -> None:
        super().__init__()
        self.fc = nn.Linear(input_size, output_size)
    def forward(self, input):
        output = self.fc(input)
        print(input.size(), output.size())

        return output 

In [10]:
model = Model(input_size, output_size)
if torch.cuda.device_count() > 1:
  print("Let's use", torch.cuda.device_count(), "GPUs!")
  # dim = 0 [30, xxx] -> [10, ...], [10, ...], [10, ...] on 3 GPUs
  model = nn.DataParallel(model)

model.to(device)

Model(
  (fc): Linear(in_features=5, out_features=2, bias=True)
)

In [11]:
for data in rand_loader:
    input = data.to(device)
    output = model(input)
    print("Outside: input size", input.size(),
          "output_size", output.size())

torch.Size([30, 5]) torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
torch.Size([30, 5]) torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
torch.Size([30, 5]) torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
torch.Size([30, 5]) torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
torch.Size([30, 5]) torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
torch.Size([30, 5]) torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
torch.Size([20, 5]) torch.Size([20, 2])
Outside: input size torch.Size([20, 5]) output_size torch.Size([20, 2])
